### ISSUE TITLE
Adding System.IdentityModel.Tokens.Jwt 3.0.1 via NuGet doesn't work

### ISSUE THREAD

**Issue by brockallen** [microsoft/azure-activedirectory-jwt-token-handler-for-dotnet#11]
When I add v3.0.1 via Nuget, I get an odd packages.config at the solution level in VS and the assembly is not referenced to the project.  Also, the local project does not get the entry needed in .packages.

To repro:
File -> New Project -> Empty Web Project
NuGet -> Add System.IdentityModel.Tokens.Jwt

At this point the odd packages.config is created at the solution level and the assembly is not referenced in the project. When I add the assembly reference manually, I still can't seem to get anything to compile.

Anyway, I think your 3.0.1 NuGet package is borked.

**Comment by brandwe** [comment]
Thanks. We could repro this. We are investigating and hope to get a fix out very soon.

**Comment by brandwe** [comment]
This has been fixed in 3.0.2. Your NuGet should automatically get updated. Re-open if you still have an issue.

**Comment by leastprivilege** [comment]
seems to work now.
