### ISSUE TITLE
Produce OpenID Connect compliant JWTs

### ISSUE THREAD

**Issue by leastprivilege** [microsoft/azure-activedirectory-jwt-token-handler-for-dotnet#13]
Hi, 

when will this code
https://github.com/MSOpenTech/azure-activedirectory-jwt-token-hander-for-dotnet/commit/a8d136354bbbe3c67aecc73989905c4699fc9b64

go into a public nuget package?

**Comment by leastprivilege** [comment]
no answer in 10 days? really?

**Comment by brandwe** [comment]
Really. We are swamped with BUILD work right now. I don't know when we will be releasing the NuGets next, but we currently are on plan to refresh every 3 months with the rest of Azure. We are looking in to building Previews using mygit in the future.

**Comment by leastprivilege** [comment]
OK. Thanks for the heads up.

On real open source projects a 10 day delay in an answer for a simple question almost means the project is "dead". So that's something to improve. A roadmap of some sort would be also useful.

**Comment by brentschmaltz** [comment]
We are going to be merging owin into dev and I expect to merge these together.

**Comment by brentschmaltz** [comment]
We have merged in the code needed for Katana and put it here:
https://github.com/MSOpenTech/azure-activedirectory-identitymodel-extensions-for-dotnet/

this repo will be retired.

**Comment by brandwe** [comment]
We may maintain both repos for a period of time. If so, we will need to do a drop here as well. We are investigating.

**Comment by brentschmaltz** [comment]
Code is in.
