### ISSUE TITLE
License isn't open enough

### ISSUE THREAD

**Issue by haf** [microsoft/azure-activedirectory-jwt-token-handler-for-dotnet#2]
The license at http://go.microsoft.com/fwlink/?LinkId=301992 states that this code can only be run on Windows systems. That's a real shame, because it means that even though we run Windows servers, Active Directory, SQL Server and the whole shebang I can't use WIF and this project to verify tokens for services running on linux if the verification code should run on the same node.

**Comment by clca** [comment]
Hi Haf,

It is a 'just' a bug. This project started from an existing codebase that he inherited from Microsoft, we missed few places where we should have updated the code before pushing it on the public repo. We are removing the license reference. The whole project is under the Apache 2 license so you can use the code on other platforms as well.

**Comment by haf** [comment]
Does that mean that we can cooperate on making this project in this github repository work on mono?

**Comment by clca** [comment]
Yes all contributions are welcome! and it would be great to have the library to run on Mono. Feel free to send us a pull request :) (if you plan to contribute please sign the CLA at https://cla.msopentech.com).

**Comment by brandwe** [comment]
This has been fixed with new license.

**Comment by haf** [comment]
Thanks, I'll open a new one about the open sourcing of the dependencies so that it's usable with the changed license.

**Comment by haf** [comment]
Btw; I really appreciate the dialog and your helpful inclination! I understand that this issue and the one I just opened are easier said than done and appreciate that it might take both time and effort from your side. Much appreciated.
