### ISSUE TITLE
Roadmap for this repo

### ISSUE THREAD

**Issue by leastprivilege** [microsoft/azure-activedirectory-jwt-token-handler-for-dotnet#5]
Hi, 

what's the intention of this repo? Just making the source code available - or are you planning to make it an OSS project?
- Will you take PRs (like this one: https://github.com/MSOpenTech/azure-activedirectory-jwt-token-hander-for-dotnet/pull/1)
- Will you merge them in a timely fashion?
- Will you update the nuget in a timely fashion when the PRs are merged?
- Do I need to sign anything to contribute?

thanks
dominick

**Comment by brandwe** [comment]
Hello Dominic.

This is a real OSS project, certainly. We are still learning how best to make this work, so it may be a little rough at first :-) I appreciate your feedback and helping us understand the expectations around the process.

To answer your questions:
1. Yes, we will take PR like yours. 
2. Timely fashion is open to interpretation, but we will try to get them merged in to a branch within a few weeks
3. Updating the Nuget right now is on a 3 month process which matches the rest of Windows Azure. We need to do the same due diligence we do with all Microsoft releases, and so we take the time to make sure it's right and ready.
4. Yes, you need to sign the Contribution Agreement (just once) and then it's in effect going forward for any PR you may make. 

Here it is: https://cla.msopentech.com/

Again, we are learning as we go - thanks for jumping in!
